name: Log Processor - Release

on:
  push:
    branches:
      - main
    paths:
      - 'apps/log-processor/**'
      - '.github/workflows/apps-log-processor-release.yml'

defaults:
  run:
    working-directory: ./apps/log-processor

jobs:
  build:
    # Only perform release if commit message does not contain 'norelease'
    if: ${{ !contains(github.event.head_commit.message, 'norelease') }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.22'

      - name: Test
        run: |
          make test

      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.1
        id: create_tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fetch_all_tags: true
          tag_prefix: "apps/log-processor/v"

      - name: Set version vars
        id: set-version-vars
        run: |
          echo "GITHUB_VERSION=${{ steps.create_tag.outputs.new_version }}" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            apps/log-processor/build/log-processor*
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Run build & push (no need to manually push - buildx does it auto)
        run: |
          make docker/build
