name: Log Processor - Pull Request

on:
  pull_request:
    paths:
      - 'apps/log-processor/**'
      - '.github/workflows/apps-log-processor-pr.yml'

defaults:
  run:
    working-directory: ./apps/log-processor

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: '~1.22'

    - uses: actions/checkout@v2

#    - name: Start up dependencies
#      run: docker-compose -f docker-compose.yaml up -d

#    - name: Wait for dependencies to start up
#      uses: jakejarvis/wait-action@master
#      with:
#        time: '30s'

    - name: Test
      run: sudo make test
