name: SDK Go - Release

on:
  push:
    branches:
      - main
    paths:
      - 'sdks/go/**'
      - '.github/workflows/sdks-go-release.yml'

defaults:
  run:
    working-directory: ./sdks/go

jobs:
  build:
    name: Tag and Release
    if: ${{ !contains(github.event.head_commit.message, 'norelease') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate new tag (dry run)
        uses: mathieudutour/github-tag-action@v6.1
        id: get_new_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          fetch_all_tags: true
          tag_prefix: "sdks/go/v"

      - name: Inject version into register.go
        run: |
          sed -i 's/LibraryVersion:.*/LibraryVersion: "${{ steps.get_new_version.outputs.new_version }}",/' register.go

      # We do this because other jobs might have written to the repo while this
      # job was running and making local changes; without this pull step, we
      # might run into an error during auto-commit.
      - name: Pull latest changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --depth=10

      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto_commit
        with:
          commit_message: Bumped version in register.go to ${{ steps.get_new_version.outputs.new_version }}

      # .. and now create the actual tag (will be the same as the dry run)
      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.1
        id: create_tag
        with:
          commit_sha: ${{ steps.auto_commit.outputs.commit_hash }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.get_new_version.outputs.new_version }}
          tag_prefix: "sdks/go/v"

