name: SDK Node - Release

on:
  push:
    branches:
      - main
    paths:
      - 'sdks/node/**'
      - '.github/workflows/sdks-node-release.yml'

defaults:
  run:
    working-directory: ./sdks/node

jobs:
  build:
    name: Tag and Release
    if: ${{ !contains(github.event.head_commit.message, 'norelease') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm install --force

      - name: Test
        run: npm run test

      - name: Generate new tag (dry run)
        uses: mathieudutour/github-tag-action@v6.1
        id: get_new_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          fetch_all_tags: true
          tag_prefix: "sdks/node/v"

      # We do this because other jobs might have written to the repo while this
      # job was running and making local changes; without this pull step, we
      # might run into an error when performing the auto-commit.
      - name: Pull latest changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --depth=10          

      - name: Update npm package version
        run: |
          npm --no-git-tag-version version ${{ steps.get_new_version.outputs.new_version }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        id: auto_commit
        with:
          commit_message: Bumped npm package version to ${{ steps.get_new_version.outputs.new_version }}

      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.1
        id: create_tag
        with:
          commit_sha: ${{ steps.auto_commit.outputs.commit_hash }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.get_new_version.outputs.new_version }}
          tag_prefix: "sdks/node/v"

      - name: Build
        run: npm run build

      - name: Release to npm
        working-directory: ./sdks/node/build
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

